# Generated by Django 4.0.1 on 2022-01-19 13:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Item's Name")),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description (Optional)')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Price')),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=200, verbose_name='Destination Address')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='ShipmentThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.item', verbose_name='item')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.shipment', verbose_name='shipment')),
            ],
            options={
                'db_table': 'shipment_through',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='items',
            field=models.ManyToManyField(related_name='shipments', through='dashboard.ShipmentThrough', to='dashboard.Item', verbose_name='Items'),
        ),
    ]
